# SPDX-FileCopyrightText: Ferdinand Thiessen <opensource@fthiessen.de>
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "Cashbook"
SPDX-PackageSupplier = "Ferdinand Thiessen <opensource@fthiessen.de>"

[[annotations]]
path = ["package-lock.json", "package.json", "composer.json", "composer.lock", "vendor-bin/*/composer.json", "vendor-bin/*/composer.lock"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Ferdinand Thiessen <opensource@fthiessen.de>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [".nvmrc", "tsconfig.json", ".github/renovate.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Ferdinand Thiessen <opensource@fthiessen.de>"
SPDX-License-Identifier = "CC0-1.0"
